spring.application.name=bingo-back

spring.datasource.url=jdbc:postgresql://localhost:5432/christmas_bingo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=lucas
spring.datasource.password=lucas
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true