spring.application.name=bingo-back

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.data-locations=classpath:data-prod.sql
# spring.sql.init.mode=never

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true